[2024-07-22T00:47:54.235+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T00:47:54.256+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_operator_v2.Greet manual__2024-07-22T00:45:51.479575+00:00 [queued]>
[2024-07-22T00:47:54.264+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_operator_v2.Greet manual__2024-07-22T00:45:51.479575+00:00 [queued]>
[2024-07-22T00:47:54.264+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-07-22T00:47:54.280+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Greet> on 2024-07-22 00:45:51.479575+00:00
[2024-07-22T00:47:54.286+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1265) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T00:47:54.287+0000] {standard_task_runner.py:63} INFO - Started process 1266 to run task
[2024-07-22T00:47:54.287+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_operator_v2', 'Greet', 'manual__2024-07-22T00:45:51.479575+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_pythonOperator.py', '--cfg-path', '/tmp/tmp5v23y2vl']
[2024-07-22T00:47:54.289+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask Greet
[2024-07-22T00:47:54.332+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_python_operator_v2.Greet manual__2024-07-22T00:45:51.479575+00:00 [running]> on host eefce25a52e3
[2024-07-22T00:47:54.432+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_python_operator_v2' AIRFLOW_CTX_TASK_ID='Greet' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T00:45:51.479575+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T00:45:51.479575+00:00'
[2024-07-22T00:47:54.433+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T00:47:54.447+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T00:47:54.448+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_pythonOperator.py", line 13, in greet
    f" and I am {age} years old")
                 ^^^
NameError: name 'age' is not defined
[2024-07-22T00:47:54.461+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_operator_v2, task_id=Greet, run_id=manual__2024-07-22T00:45:51.479575+00:00, execution_date=20240722T004551, start_date=20240722T004754, end_date=20240722T004754
[2024-07-22T00:47:54.477+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task Greet (name 'age' is not defined; 1266)
[2024-07-22T00:47:54.501+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-22T00:47:54.524+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T00:47:54.528+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
