[2024-07-22T00:19:16.438+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T00:19:16.467+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.second_task manual__2024-07-22T00:19:14.173166+00:00 [queued]>
[2024-07-22T00:19:16.479+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.second_task manual__2024-07-22T00:19:14.173166+00:00 [queued]>
[2024-07-22T00:19:16.479+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-22T00:19:16.498+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): second_task> on 2024-07-22 00:19:14.173166+00:00
[2024-07-22T00:19:16.506+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=890) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T00:19:16.508+0000] {standard_task_runner.py:63} INFO - Started process 892 to run task
[2024-07-22T00:19:16.508+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'second_task', 'manual__2024-07-22T00:19:14.173166+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp840yu44g']
[2024-07-22T00:19:16.510+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask second_task
[2024-07-22T00:19:16.577+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v4.second_task manual__2024-07-22T00:19:14.173166+00:00 [running]> on host eefce25a52e3
[2024-07-22T00:19:16.730+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T00:19:14.173166+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T00:19:14.173166+00:00'
[2024-07-22T00:19:16.731+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T00:19:16.749+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-22T00:19:16.750+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hey, I am task2 and will be running after task 1']
[2024-07-22T00:19:16.764+0000] {subprocess.py:86} INFO - Output:
[2024-07-22T00:19:16.766+0000] {subprocess.py:93} INFO - Hey, I am task2 and will be running after task 1
[2024-07-22T00:19:16.767+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-22T00:19:16.768+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T00:19:16.807+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=second_task, run_id=manual__2024-07-22T00:19:14.173166+00:00, execution_date=20240722T001914, start_date=20240722T001916, end_date=20240722T001916
[2024-07-22T00:19:16.843+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-22T00:19:16.853+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
